# Generated by Django 4.2 on 2023-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default='gney', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
